-- MySQL Script generated by MySQL Workbench
-- Fri Jan 10 13:54:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kizzdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kizzdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kizzdatabase` ;
USE `kizzdatabase` ;

-- -----------------------------------------------------
-- Table `kizzdatabase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kizzdatabase`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kizzdatabase`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kizzdatabase`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NOT NULL,
  `domaine` VARCHAR(45) NULL,
  `point` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kizzdatabase`.`assertions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kizzdatabase`.`assertions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(45) NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_assertions_questions1_idx` (`question_id` ASC) ,
  CONSTRAINT `fk_assertions_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `kizzdatabase`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kizzdatabase`.`reponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kizzdatabase`.`reponses` (
  `id` INT NOT NULL,
  `assertion_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_reponses_assertions1_idx` (`assertion_id` ASC) ,
  INDEX `fk_reponses_questions1_idx` (`question_id` ASC) ,
  INDEX `fk_reponses_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_reponses_assertions1`
    FOREIGN KEY (`assertion_id`)
    REFERENCES `kizzdatabase`.`assertions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponses_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `kizzdatabase`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponses_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kizzdatabase`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kizzdatabase`.`correctes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kizzdatabase`.`correctes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `assertion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_correctes_questions_idx` (`question_id` ASC) ,
  INDEX `fk_correctes_assertions1_idx` (`assertion_id` ASC) ,
  CONSTRAINT `fk_correctes_questions`
    FOREIGN KEY (`question_id`)
    REFERENCES `kizzdatabase`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_correctes_assertions1`
    FOREIGN KEY (`assertion_id`)
    REFERENCES `kizzdatabase`.`assertions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
